name: auth0_flutter_platform_interface
description: A common platform interface for the auth0_flutter federated plugin.
version: 1.0.1

homepage: https://github.com/auth0/auth0-flutter

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.0

dev_dependencies:
  build_runner: ^2.1.8
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  mockito: ^5.1.0
  test: ^1.19.5

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
